version: '3.8'

services:
  twitch-alert-discord-bot:
    build: .
    container_name: twitch-alert-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
