services:
  twitch-alert-discord-bot:
    build: .
    container_name: twitch-alert-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 256M
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
